blog/urls.py
from django.urls import path
from .views import PostListView

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    def __str__(self):
       return self.title
    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Post

# Create your views here.

class PostListView(ListView):
    model = Post
    template_name = 'home.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Blog Django May</title>
</head>
<body>
    <header>
        <a href="{%url 'home' %}"><h1>Blog Django<h1><a>
        </header>
    {% block content %}
    {% endblock content %}

</body>
</html>

templates/home.html
<!-- heredo de la base -->
{% extends "base.html" %}

{% block content%}
    {% for post in post_list%}
       <a href=""><h2> {{post.title}}</h2><a>
       <p>{{post.body}}</p>
    {% endfor %}
{% endblock content %}